Fix/download trivyignore in dockerfile
olxbr/aws-ecr-push-action pull request #37
Opened 2021-11-03 18:59 UTC by vmattos

2021-11-04 17:46 UTC, jeffbraga requested changes
@vmattos Could u please change the 'hardcoded' URL to parameter on build-args ? like
```
  executeSyncCmd(
    'docker',
    [
      'build',
      '-f',
      `${dockerfileName}`,
      '-t',
      `${suspectImageName}`,
      '--build-arg',
      `REGISTRY=${ECR_ENDPOINT}`,
      '--build-arg',
      'CLAMAV_IMAGE=cross/devsecops/clamav:latest',
      '--build-arg',
      'TRIVY_IMAGE=cross/devsecops/trivy:latest',
      '--build-arg',
      'BASE_IMAGE=base_images/alpine:3.14-base',
      '--build-arg',
      `TARGET_IMAGE=${config.repositoryNames[0]}:${config.tags[0]}`,
      '--build-arg',
      `TRIVY_SEVERITY=${minimalSeverity}`,
      '--build-arg',
      `TRIVY_IGNORE_URL=${triveIgnoreUrl}`,
      '.'
    ]
  );```

2021-11-05 19:27 UTC, jeffbraga approved these changes
AMAZING @vmattos !

2021-11-09 18:26 UTC, julianoborba approved these changes

2021-11-09 19:18 UTC, marciorgb approved these changes

2021-11-10 14:27 UTC, merged